FORMAT: 1A
HOST: localhost:4000

# API

my first api restfull example


## api [/api]
just one object with one property name

### Create [POST /api/create]
+ Response 200 (application/json)
{
    "user": "user created successfully"
}


### show  [GET /api/show]
+ Response 200 (application/json)

### update [POST /api/update]
+ Response 200 (application/json)
{
    "unable to update the database"
}

### delete [POST /api/delete]
+ Response 200 (application/json)
{
    "Successfully removed"
}

### search [POST /api/search]
+ Response 200 (application/json)
{
    "search find"
}